-- ── LEXCUSTOMS DATABASE SETUP SCHEMA ──
-- Copy and paste this script into your Supabase SQL Editor (https://supabase.com) and click Run.

-- 1. Create Norms Table
CREATE TABLE IF NOT EXISTS public.norms (
    norm_id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    domain TEXT NOT NULL,
    status TEXT NOT NULL,
    contested BOOLEAN NOT NULL DEFAULT false,
    summary TEXT NOT NULL,
    primary_codification TEXT,
    state_practice JSONB NOT NULL DEFAULT '[]'::jsonb,
    opinio_juris JSONB NOT NULL DEFAULT '[]'::jsonb,
    sources JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (optional, server-side service role will bypass)
ALTER TABLE public.norms ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access to norms" ON public.norms FOR SELECT USING (true);

-- 2. Create Users Table
CREATE TABLE IF NOT EXISTS public.users (
    username TEXT PRIMARY KEY,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- 3. Create Search Logs Table
CREATE TABLE IF NOT EXISTS public.search_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query TEXT NOT NULL,
    results_count INTEGER NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.search_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public inserts on search logs" ON public.search_logs FOR INSERT WITH CHECK (true);

-- 4. Create Analytics Views Table
CREATE TABLE IF NOT EXISTS public.analytics_views (
    norm_id TEXT PRIMARY KEY REFERENCES public.norms(norm_id) ON DELETE CASCADE,
    views INTEGER NOT NULL DEFAULT 0
);

ALTER TABLE public.analytics_views ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access to analytics views" ON public.analytics_views FOR SELECT USING (true);
